Add GoogleFetcher
apache/tika pull request #2074
Opened 2024-12-04 19:46 UTC by bartek

This allows the fetching of items using files.get from Google Drive

Thanks for your contribution to [Apache Tika](https://tika.apache.org/)! Your help is appreciated!

Before opening the pull request, please verify that
* there is an open issue on the [Tika issue tracker](https://issues.apache.org/jira/projects/TIKA) which describes the problem or the improvement. We cannot accept pull requests without an issue because the change wouldn't be listed in the release notes.
* the issue ID (`TIKA-XXXX`)
  - is referenced in the title of the pull request
  - and placed in front of your commit messages surrounded by square brackets (`[TIKA-XXXX] Issue or pull request title`)
* commits are squashed into a single one (or few commits for larger changes)
* Tika is successfully built and unit tests pass by running `mvn clean test`
* there should be no conflicts when merging the pull request branch into the *recent* `main` branch. If there are conflicts, please try to rebase the pull request branch on top of a freshly pulled `main` branch
* if you add new module that downstream users will depend upon add it to relevant group in `tika-bom/pom.xml`.

We will be able to faster integrate your pull request if these conditions are met. If you have any questions how to fix your problem or about using Tika in general, please sign up for the [Tika mailing list](http://tika.apache.org/mail-lists.html). Thanks!

2024-12-04 20:10 UTC, tballison requested changes
Do you want to merge this into main? Or actually just the tika-grpc-3x-features?

If we merge to main, I'll cherrypick back to 3x.

We're 4x/main is now the dev branch.

2024-12-04 20:15 UTC, bartek commented
@tballison Thanks for review! Honestly, I wasn't expecting one as I'm mostly pushing this to collaborate with @nddipiazza, however, if it makes sense to work as a group, then I will happily do so.

I am pushing to `tika-grpc-3x-features` as that is the branch we're working off in terms of using the tika-pipes project, but I'm not sure on the overall state of things -- if you have a clearer picture, it'd be great to know.

Happy to hop on a quick call if it's easier. I'll read your other comments in the meantime :+1:

2024-12-04 20:22 UTC, bartek commented
> To the degree we can make small/logical changes in main to achieve the project's goals, all the better? This is definitely a standalone PR that can go straight into main, I think.

Sounds great, I'm glad you think so. Let me sort out your feedback and then we'll go from there. Appreciate the response!

2024-12-05 01:58 UTC, bartek commented on tika-pipes/tika-fetchers/tika-fetcher-google/pom.xml
> +        <version>3.0.0-SNAPSHOT</version>
3.0.0-SNAPSHOT is referenced in many of the pom.xml files inside tika-pipes. I can update this Google Fetcher to reference `4.0.0-SNAPSHOT`, but should there be a separate PR to get everything else on the same version identifier?

2024-12-05 13:56 UTC, bartek commented on tika-pipes/tika-fetchers/tika-fetcher-google/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
Added in fixup: https://github.com/apache/tika/pull/2074/commits/40476c19f7fcfdb98fc0e80f892bd13b4ab5a664

2024-12-05 13:56 UTC, bartek commented on tika-pipes/tika-fetchers/tika-fetcher-google/src/main/java/org/apache/tika/pipes/fetchers/google/GoogleFetcher.java
> +                    File tempFile = Files.createTempFile("spooled-temp", ".dat").toFile();
Thanks, used in this fixup: https://github.com/apache/tika/pull/2074/commits/0823d12a60f7dfb6f45e724f556ecb2e791dbcd6

2024-12-05 14:47 UTC, bartek commented on tika-pipes/tika-fetchers/tika-fetcher-google/src/main/java/org/apache/tika/pipes/fetchers/google/GoogleDriveFetcher.java
Renamed to GoogleDriveFetcher as the [files.get](https://developers.google.com/drive/api/reference/rest/v3/files/get) call is part of the Google Drive API

I don't expect this fetcher to service other Google APIs, and the fetchKey/configuration is kept simple by narrowing the fetchers scope

2024-12-05 18:42 UTC, bartek commented on tika-pipes/tika-fetchers/tika-fetcher-google/pom.xml
> +        <version>3.0.0-SNAPSHOT</version>
I pushed https://github.com/apache/tika/pull/2074/commits/da30edef4bf7f62468cd1a21abdb0894e48e61a5, hopefully this satisfies what you were expecting?

I can also adjust the merge-to branch to be `main`. Are all the changes inside tika-grpc-3x-features in main? (excluding this one)

2024-12-05 22:38 UTC, tballison commented
Sorry, what I meant was that over on the tika-grpc-3x branch you should change everything to 4.0.0-SNAPSHOT. On this PR, you should only need to do that for the GoogleDriveFetcher, and you should make this PR against `main`.

2024-12-06 00:47 UTC, bartek commented
> Sorry, what I meant was that over on the tika-grpc-3x branch you should change everything to 4.0.0-SNAPSHOT. On this PR, you should only need to do that for the GoogleDriveFetcher, and you should make this PR against main.

No worries, made that change here: https://github.com/apache/tika/pull/2074/commits/d439aca4bef3960215b7c363b00886a318fb3937

2024-12-06 16:29 UTC, closed without merging

2024-12-06 16:29 UTC, bartek commented
Closing this in favour of https://github.com/apache/tika/pull/2077, which is based off `main` and targeting it. The tika-grpc-3x-features branch needs significant cleanup.